---
language: bash
dist: xenial

before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.2/terraform_0.12.2_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - sudo mv /tmp/terraform /usr/local/bin/

env:
  - AWS_REGION=us-east-1

script:
  - terraform init
  - terraform validate
  - terraform fmt -write=false -list=true -diff=true -check=true
